const constants = {
	SET_APIDATA: "SET_APIDATA",
	SET_LOADING: "SET_LOADING",
	SET_TIME_SINCE_UPDATE: "SET_TIME_SINCE_UPDATE",
	SET_CURRENCY: "SET_CURRENCY",
	SET_SORT_BY: "SET_SORT_BY",
	SET_SORT_DIRECTION: "SET_SORT_DIRECTION"
}

export default constants

